apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-server
spec:
  selector:
    matchLabels:
      app: server-pod
  template:
    metadata:
      name: server-pod
      annotations:
        ad.datadoghq.com/server.logs: '[{"source":"python","service":"assistant-openai"}]'
      labels:
        app: server-pod
        environment: production
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: r4deu51/assistant-openai:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '0.1'
              memory: '100Mi'
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: OPENAI_API_KEY

            - name: ASSISTANT_ID
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: ASSISTANT_ID
