apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server-pod
spec:
  containers:
    - name: server
      image: r4deu51/assistant-openai:latest
      ports:
        - containerPort: 3000
      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: OPENAI_API_KEY

        - name: ASSISTANT_ID
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: ASSISTANT_ID
      resources:
        limits:
          cpu: '0.7'
          memory: '500Mi'
