name: Deploy Lambda Functions

on: 
  workflow_dispatch: 
    inputs:
      function_name:
        required: true
        description: The name of function to do deploy
        options:
          - create_chat
          - publish_message
          - get_message
        type: choice

      environment:
        required: false
        description: The environment/stage to do deploy
        default: staging
        options:
          - staging
          - production
        type: choice
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-python-requirements && serverless deploy --stage ${{ inputs.environment }} -f ${{ inputs.function_name }}"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
